
CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`burgername` VARCHAR(255) NOT NULL,
	`eaten` BOOLEAN DEFAULT false,
	PRIMARY KEY (id),
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
